default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: mysecretpassword
  host: 0.0.0.0
  port: 5432
  pool: 5

development:
  <<: *default
  database: stevo_06_18_development
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>

test:
  <<: *default
  database: stevo_06_18_test
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
